#!/bin/bash
# Script to compile and run application

echo "Compiling database reader..."

javac -g sandbox/mnist/MNISTDatabase.java

echo "Compilation of database reader complete"
echo "Compiling neuron..."

javac -g sandbox/mnist/Neuron.java

echo "Compilation of neuron complete"
echo "Compiling perceptron..."

javac -g sandbox/mnist/Perceptron.java

echo "Compilation of perceptron complete"
echo "Compiling application..."

javac -g sandbox/mnist/Application.java

echo "Compilation of application complete"
echo "Running application..."

java sandbox.mnist.Application
