#!/bin/bash
# Script to print database content to files

echo "Compiling database reader..."

javac -g sandbox/mnist/MNISTDatabase.java

echo "Compilation of database reader complete"
echo "Compiling printer..."

javac -g sandbox/mnist/Printer.java

echo "Compilation of printer complete"
echo "Running printer..."

java sandbox.mnist.Printer